config/routes.rb
Hacknowledge::Application.routes.draw do
  resources :prizes

  resources :swags

  resources :sponsors

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}
  
  resources :authentications
  resources :users
  resources :teams
  resources :participants
  resources :events

  root 'pages#index'

  get '/eventbrite/:eventbrite_event_id', :to => 'events#eventbrite'

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  belongs_to :event
  has_many :swags
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sponsor }
      else
        format.html { render action: 'new' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponsor_params
      params.require(:sponsor).permit(:name, :description, :url)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h1>Editing sponsor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<h1>Listing sponsors</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= link_to 'Show', sponsor %></td>
        <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
        <td><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sponsor', new_sponsor_path %>

app/views/sponsors/new.html.erb
<h1>New sponsor</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>